(spacemacs/declare-prefix "o t" "Org-files")
(defun TODOs ()
  (interactive)
  (find-file "~/GoogleDrive/Org/TODOs.org")
  )
(defun Routines ()
  (interactive)
  (find-file "~/GoogleDrive/Org/Routines.org"))
(defun Timetable ()
  (interactive)
  (find-file "~/GoogleDrive/Org/Timetable.org"))
(defun Archive ()
  (interactive)
  (find-file "~/GoogleDrive/Org/Archive.org"))
(defun Projects ()
  (interactive)
  (find-file "~/GoogleDrive/Org/Projects.org"))
(defun Study ()
  (interactive)
  (find-file "~/GoogleDrive/Org/Study.org"))
(defun Fun ()
  (interacrive)
  (find-file "~/GoogleDrive/Org/Fun.org"))
(defun Prep ()
  (interactive)
  (find-file "~/GoogleDrive/Org/Prep.org"))
(defun Emacs ()
  (interactive)
  (find-file "~/GoogleDrive/Org/Emacs.org"))
(defun Books ()
  (interactive)
  (find-file "~/GoogleDrive/Org/Books.org"))
(defun Medic ()
  (interactive)
  (find-file "~/GoogleDrive/Org/Medic.org"))
(defun Holiday ()
  (interactive)
  (find-file "~/GoogleDrive/Org/Holiday.org"))
(defun Exam ()
  (interactive)
  (find-file "~/GoogleDrive/Org/Examination.org"))

(spacemacs/set-leader-keys (kbd "SPC o t t") 'TODOs)
(spacemacs/set-leader-keys (kbd "SPC o t r") 'Routines)
(spacemacs/set-leader-keys (kbd "SPC o t T") 'Timetable)
(spacemacs/set-leader-keys (kbd "SPC o t e") 'Emacs)
(spacemacs/set-leader-keys (kbd "SPC o t E") 'Exam)
(spacemacs/set-leader-keys (kbd "SPC o t a") 'Archive)
(spacemacs/set-leader-keys (kbd "SPC o t p") 'Projects)
(spacemacs/set-leader-keys (kbd "SPC o t s") 'Study)
(spacemacs/set-leader-keys (kbd "SPC o t f") 'Fun)
(spacemacs/set-leader-keys (kbd "SPC o t P") 'Prep)
(spacemacs/set-leader-keys (kbd "SPC o t b") 'Books)
(spacemacs/set-leader-keys (kbd "SPC o t m") 'Medic)
(spacemacs/set-leader-keys (kbd "SPC o t h") 'Holiday)
;(spacemacs/set-leader-keys (kbd "SPC o t m") 'Medic)
;(spacemacs/set-leader-keys (kbd "SPC o t m") 'Medic)
;(spacemacs/set-leader-keys (kbd "SPC o t m") 'Medic)
;(spacemacs/set-leader-keys (kbd "SPC o t m") 'Medic)
;(spacemacs/set-leader-keys (kbd "SPC o t m") 'Medic)
;(spacemacs/set-leader-keys (kbd "SPC o t m") 'Medic)
;(spacemacs/set-leader-keys (kbd "SPC o t m") 'Medic)

(defun Search-Orgfiles ()
  (interactive)
  (helm-find-files-1 "~/GoogleDrive/Org/"))
(spacemacs/set-leader-keys (kbd "SPC o t /") 'Search-Orgfiles)
