 (spacemacs/declare-prefix "o n" "Notebook")
  (spacemacs/declare-prefix "o n h" "History")
  (spacemacs/declare-prefix "o n s" "Science")
  (spacemacs/declare-prefix "o n j" "Japanese")
  (defun Chemistry ()
    (interactive)
    (find-file "~/GoogleDrive/Notebooks/Chemistry")
    (spacemacs/toggle-maximize-buffer)
    (neotree-dir "~/GoogleDrive/Notebooks/Chemistry")
    )
  (defun Biology ()
    (interactive)
    (find-file "~/GoogleDrive/Notebooks/Biology")
    (spacemacs/toggle-maximize-buffer)
    (neotree-dir "~/GoogleDrive/Notebooks/Biology")
    )
  (defun Arts ()
    (interactive)
    (find-file "~/GoogleDrive/Notebooks/Arts")
    (spacemacs/toggle-maximize-buffer)
    (neotree-dir "~/GoogleDrive/Notebooks/Arts")
    )
  (defun Technology()
    (interactive)
    (find-file "~/GoogleDrive/Notebooks/Technology")
    (spacemacs/toggle-maximize-buffer)
    (neotree-dir "~/GoogleDrive/Notebooks/Technology")
    )
  (defun Mathematics()
    (interactive)
    (find-file "~/GoogleDrive/Notebooks/Mathematics")
    (spacemacs/toggle-maximize-buffer)
    (neotree-dir "~/GoogleDrive/Notebooks/Mathematics")
    )
  (defun World-History()
    (interactive)
    (find-file "~/GoogleDrive/Notebooks/Geography_and_History/World_History")
    (spacemacs/toggle-maximize-buffer)
    (neotree-dir "~/GoogleDrive/Notebooks/Geography_and_History/World_History")
    )
  (defun Earth-Science()
    (interactive)
    (find-file "~/GoogleDrive/Notebooks/Earth_Science")
    (spacemacs/toggle-maximize-buffer)
    (neotree-dir "~/GoogleDrive/Notebooks/Earth_Science")
    )
  (defun Piano()
    (interactive)
    (find-file "~/GoogleDrive/Notebooks/Arts/Music/Piano")
    (spacemacs/toggle-maximize-buffer)
    (neotree-dir "~/GoogleDrive/Notebooks/Arts/Music/Piano")
    )
  (defun English()
    (interactive)
    (find-file "~/GoogleDrive/Notebooks/English")
    (spacemacs/toggle-maximize-buffer)
    (neotree-dir "~/GoogleDrive/Notebooks/English")
    )
  (defun Deutsch()
    (interactive)
    (find-file "~/GoogleDrive/Notebooks/Deutsch")
    (spacemacs/toggle-maximize-buffer)
    (neotree-dir "~/GoogleDrive/Notebooks/Deutsch"))
  (defun Civics()
    (interactive)
    (find-file "~/GoogleDrive/Notebook/Civics/4年公民.txt")
    (spacemacs/toggle-maximize-buffer)
    (neotree-dir "~/GoogleDrive/Notebook/Civics/")
    )
  (defun Physics()
    (interactive)
    (find-file "~/GoogleDrive/Notebooks/Physics")
    (spacemacs/toggle-maximize-buffer)
    (neotree-dir "~/GoogleDrive/Notebooks/Physics")
    )
  (defun Japan()
    (interactive)
    (find-file "~/GoogleDrive/Notebooks/Geography_and_History/Asia/Japan/History")
    (spacemacs/toggle-maximize-buffer)
    (neotree-dir "~/GoogleDrive/Notebooks/Geography_and_History/Asia/Japan/History")
         )
  (defun Lyrics()
    (interactive)
    (find-file "~/GoogleDrive/Notebooks/Lyrics/Ariana Grande/Love me Harder.org")
    (spacemacs/toggle-maximize-buffer)
    (neotree-dir "~/GoogleDrive/Notebooks/Lyrics/")
    )
  (defun Parenting()
    (interactive)
    (find-file "~/GoogleDrive/Notebooks/Parenting")
    (spacemacs/toggle-maximize-buffer)
    (neotree-dir "~/GoogleDrive/Notebooks/Parenting")
    )
  (defun Sport()
    (interactive)
    (find-file "~/GoogleDrive/Notebooks/Sport")
    (spacemacs/toggle-maximize-buffer)
    (neotree-dir "~/GoogleDrive/Notebooks/Sport"))
  (defun Military()
    (interactive)
    (find-file "~/GoogleDrive/Notebooks/Military")
    (spacemacs/toggle-maximize-buffer)
    (neotree-dir "~/GoogleDrive/Notebooks/Military"))
  (defun Military()
    (interactive)
    (find-file "~/GoogleDrive/Notebooks/Religion")
    (spacemacs/toggle-maximize-buffer)
    (neotree-dir "~/GoogleDrive/Notebooks/Religion"))
  (defun 現代文()
    (interactive)
    (find-file "~/GoogleDrive/Notebooks/現代文")
    (spacemacs/toggle-maximize-buffer)
    (neotree-dir "~/GoogleDrive/Notebooks/現代文"))
  (defun 古文()
    (interactive)
    (find-file "~/GoogleDrive/Notebooks/古文")
    (spacemacs/toggle-maximize-buffer)
    (neotree-dir "~/GoogleDrive/Notebooks/古文"))
  (defun 漢文()
    (interactive)
    (find-file "~/GoogleDrive/Notebooks/古文/漢文")
    (spacemacs/toggle-maximize-buffer)
    (neotree-dir "~/GoogleDrive/Notebooks/古文/漢文"))


  (spacemacs/set-leader-keys (kbd "SPC o n a") 'Arts)
  (spacemacs/set-leader-keys (kbd "SPC o n c") 'Civics)
  (spacemacs/set-leader-keys (kbd "SPC o n l") 'Lyrics)
  (spacemacs/set-leader-keys (kbd "SPC o n m") 'Mathematics)
  (spacemacs/set-leader-keys (kbd "SPC o n j g") '現代文)
  (spacemacs/set-leader-keys (kbd "SPC o n j c") '古文)
  (spacemacs/set-leader-keys (kbd "SPC o n j k") '漢文)
  (spacemacs/set-leader-keys (kbd "SPC o n e") 'English)
  (spacemacs/set-leader-keys (kbd "SPC o n d") 'Deutsch)
  (spacemacs/set-leader-keys (kbd "SPC o n s b") 'Biology)
  (spacemacs/set-leader-keys (kbd "SPC o n s c") 'Chemistry)
  (spacemacs/set-leader-keys (kbd "SPC o n s e") 'Earth-Science)
  (spacemacs/set-leader-keys (kbd "SPC o n s p") 'Physics)
  (spacemacs/set-leader-keys (kbd "SPC o n M") 'Military)
  (spacemacs/set-leader-keys (kbd "SPC o n p") 'Parenting)
  (spacemacs/set-leader-keys (kbd "SPC o n r") 'Religion)
  (spacemacs/set-leader-keys (kbd "SPC o n t") 'Technology)
  (spacemacs/set-leader-keys (kbd "SPC o n h j") 'Japan)
  (spacemacs/set-leader-keys (kbd "SPC o n h w") 'World-History)
  (spacemacs/set-leader-keys (kbd "SPC o n S") 'Sport)

;;**** Helm-find-file Notebook
  (defun Search-Notebooks ()
    (interactive)
    (helm-find-files-1 "~/GoogleDrive/Notebooks/"))
  (spacemacs/set-leader-keys (kbd "SPC o n /") 'Search-Notebooks)
